name: base
dependencies:
  - pytorch=0.4.1
  - numpy
  - scipy
  - pandas
  - scikit-learn=0.19.1
  - nltk
  - requests
  - click
  - flask
  - unidecode
  - elasticsearch-dsl=6.1.*
  - spacy
  - pip:
      - xgboost
channels:
  - pytorch
